In [1]:
import numpy as np
from fractions import Fraction

#### Number of Webpages

In [2]:
n = 4

In [3]:
transferMatrix = np.matrix([[0,Fraction(1,2),0,0],[Fraction(1,3),0,0,Fraction(1,2)],[Fraction(1,3),0,0,Fraction(1,2)],[Fraction(1,3),Fraction(1,2),1,0]])
print(transferMatrix)

[[0 Fraction(1, 2) 0 0]
 [Fraction(1, 3) 0 0 Fraction(1, 2)]
 [Fraction(1, 3) 0 0 Fraction(1, 2)]
 [Fraction(1, 3) Fraction(1, 2) 1 0]]


In [4]:
constantMatrix= np.zeros((n,n))
constantMatrix[:] = Fraction(1,n)
print(constantMatrix)

[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]


In [5]:
dampingFactor = 0.85

In [6]:
pageRankMatrix = dampingFactor * transferMatrix + ((1-dampingFactor) * constantMatrix)
print(pageRankMatrix)

[[0.037500000000000006 0.4625 0.037500000000000006 0.037500000000000006]
 [0.3208333333333333 0.037500000000000006 0.037500000000000006 0.4625]
 [0.3208333333333333 0.037500000000000006 0.037500000000000006 0.4625]
 [0.3208333333333333 0.4625 0.8875 0.037500000000000006]]


## Power Iteration Method

In [7]:
probability= np.zeros((n,1))
probability[:] = Fraction(1,n)
print(probability)

[[0.25]
 [0.25]
 [0.25]
 [0.25]]


In [8]:
probabilityOld = probability

In [9]:
for i in range(100000):
    probability = pageRankMatrix * probability
    if (probabilityOld == probability).all():
        break
    probabilityOld = probability
print (probability)

[[0.1392191078634532]
 [0.23933907732577211]
 [0.23933907732577211]
 [0.3821027374850045]]


### Probabilities of webpages are above

So Rank of webpages
1. 4
2. 2,3
3. 1

## Eigenvalue Method

In [10]:
eigenvalue, eigenvector = np.linalg.eig(np.array(pageRankMatrix, dtype=float))
print(eigenvalue)
print(eigenvector)

[ 1.00000000e+00 -7.72011047e-01 -7.79889531e-02  5.77912571e-16]
[[ 2.63122478e-01  2.62323812e-01 -8.25340062e-01 -8.01783726e-01]
 [ 4.52348045e-01 -4.76510307e-01  1.51452723e-01 -1.30083707e-15]
 [ 4.52348045e-01 -4.76510307e-01  1.51452723e-01  2.67261242e-01]
 [ 7.22169685e-01  6.90696802e-01  5.22434615e-01  5.34522484e-01]]


In [11]:
requiredEigenvector = eigenvector[:,0].reshape(n,1)  # Eigenvalue = 1 for first column
requiredEigenvector = requiredEigenvector/np.sum(requiredEigenvector, axis = 0) # Convert to Probabilities
print(requiredEigenvector) # Probabilities of webpages

[[0.13921911]
 [0.23933908]
 [0.23933908]
 [0.38210274]]


So Rank of webpages
1. 4
2. 2,3
3. 1