In [1]:
import numpy as np
import pandas as pd
import fileinput

# Open Systems

Number of Sectors (n)

In [2]:
n=4

In [3]:
model = fileinput.input('leontief_data.txt')
next(model)

'sector1, sector2, sector3, sector4\n'

In [4]:
consumptionMatrix = np.loadtxt(model, dtype='f', delimiter=',')
print(consumptionMatrix)

[[0.1  0.05 0.3  0.2 ]
 [0.15 0.25 0.05 0.1 ]
 [0.3  0.1  0.1  0.25]
 [0.15 0.2  0.1  0.2 ]]


In [5]:
identityMatrix = np.identity(n)
print(identityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
demandVector = np.array([25000, 10000, 30000, 50000])
demandVector = demandVector.reshape(n,1)
print(demandVector)

[[25000]
 [10000]
 [30000]
 [50000]]


In [7]:
totalProduction = np.linalg.solve(identityMatrix-consumptionMatrix,demandVector)
print(totalProduction)

[[ 85580.99081969]
 [ 50622.97846945]
 [ 96157.86103972]
 [103221.91441587]]


# Closed Systems

Number of Sectors (n)

In [8]:
n=3

In [9]:
consumptionMatrix = np.loadtxt("model.csv", dtype='f', delimiter=',')
print(consumptionMatrix)

[[0.1 0.4 0. ]
 [0.2 0.4 0.9]
 [0.7 0.2 0.1]]


In [10]:
eigenvalue, eigenvector = np.linalg.eig(consumptionMatrix)
print(eigenvalue)
print(eigenvector)

[ 1.        +0.j        -0.19999999+0.4358899j -0.19999999-0.4358899j]
[[-0.36048698+0.j         -0.28347337-0.41187724j -0.28347337+0.41187724j]
 [-0.8110957 +0.j          0.6614378 +0.j          0.6614378 -0.j        ]
 [-0.46062225+0.j         -0.37796447+0.41187724j -0.37796447-0.41187724j]]


In [11]:
counter = 0
for x in eigenvalue:
    if x == 1:
        break
    counter = counter + 1
solution = eigenvector[:,counter].reshape(n,1)
print(solution)

[[-0.36048698+0.j]
 [-0.8110957 +0.j]
 [-0.46062225+0.j]]


### The above solution will remain solution after scaling